<?php

declare(strict_types=1);

/*
 * Référentiel des principaux employeurs publics camerounais.
 *
 * Sources officielles consultées le 23 juillet 2026 :
 * - Services du Premier ministre, « Organisation du Gouvernement » :
 *   https://spm.gov.cm/site/?q=fr/content/organisation-du-gouvernement
 * - MINFI / CTR, « Rapport sur la situation des entreprises et établissements
 *   publics au 31 décembre 2022 » :
 *   https://ctr.cm/wp-content/uploads/2024/02/RSEP-2022-Fr-final.pdf
 * - MINESUP, liste des universités d'État :
 *   https://www.minesup.gov.cm/index.php/2025/09/
 *
 * La liste est volontairement complétée par une option « Autre » côté
 * frontend : le portefeuille public évolue et aucune candidature ne doit être
 * bloquée par l'absence ponctuelle d'un organisme.
 */
return [
    'Institutions et administrations centrales' => [
        'Présidence de la République',
        'Services du Premier ministre',
        'Assemblée nationale',
        'Sénat',
        'Conseil constitutionnel',
        'Cour suprême',
        'Chambres des Comptes de la Cour suprême',
        'Contrôle supérieur de l’État (CONSUPE)',
        'Délégation générale à la Sûreté nationale (DGSN)',
        'Ministère de l’Administration territoriale (MINAT)',
        'Ministère de l’Agriculture et du Développement rural (MINADER)',
        'Ministère des Affaires sociales (MINAS)',
        'Ministère des Arts et de la Culture (MINAC)',
        'Ministère du Commerce (MINCOMMERCE)',
        'Ministère de la Communication (MINCOM)',
        'Ministère de la Décentralisation et du Développement local (MINDDEVEL)',
        'Ministère de la Défense (MINDEF)',
        'Ministère des Domaines, du Cadastre et des Affaires foncières (MINDCAF)',
        'Ministère de l’Eau et de l’Énergie (MINEE)',
        'Ministère de l’Économie, de la Planification et de l’Aménagement du territoire (MINEPAT)',
        'Ministère de l’Éducation de base (MINEDUB)',
        'Ministère de l’Élevage, des Pêches et des Industries animales (MINEPIA)',
        'Ministère de l’Emploi et de la Formation professionnelle (MINEFOP)',
        'Ministère de l’Enseignement supérieur (MINESUP)',
        'Ministère des Enseignements secondaires (MINESEC)',
        'Ministère de l’Environnement, de la Protection de la nature et du Développement durable (MINEPDED)',
        'Ministère des Finances (MINFI)',
        'Ministère de la Fonction publique et de la Réforme administrative (MINFOPRA)',
        'Ministère des Forêts et de la Faune (MINFOF)',
        'Ministère de l’Habitat et du Développement urbain (MINHDU)',
        'Ministère de la Jeunesse et de l’Éducation civique (MINJEC)',
        'Ministère de la Justice (MINJUSTICE)',
        'Ministère des Marchés publics (MINMAP)',
        'Ministère des Mines, de l’Industrie et du Développement technologique (MINMIDT)',
        'Ministère des Petites et Moyennes Entreprises, de l’Économie sociale et de l’Artisanat (MINPMEESA)',
        'Ministère des Postes et Télécommunications (MINPOSTEL)',
        'Ministère de la Promotion de la Femme et de la Famille (MINPROFF)',
        'Ministère de la Recherche scientifique et de l’Innovation (MINRESI)',
        'Ministère des Relations extérieures (MINREX)',
        'Ministère de la Santé publique (MINSANTE)',
        'Ministère des Sports et de l’Éducation physique (MINSEP)',
        'Ministère du Tourisme et des Loisirs (MINTOUL)',
        'Ministère des Transports (MINT)',
        'Ministère du Travail et de la Sécurité sociale (MINTSS)',
        'Ministère des Travaux publics (MINTP)',
    ],
    'Entreprises et établissements publics' => [
        'Aéroports du Cameroun (ADC)',
        'Agence d’Électrification Rurale (AER)',
        'Agence de Promotion des Petites et Moyennes Entreprises (APME)',
        'Agence de Régulation des Télécommunications (ART)',
        'Agence de Régulation du Secteur de l’Électricité (ARSEL)',
        'Agence Nationale d’Appui au Développement Forestier (ANAFOR)',
        'Agence Nationale de Radioprotection (ANRP)',
        'Agence Nationale des Technologies de l’Information et de la Communication (ANTIC)',
        'Autorité Portuaire Nationale (APN)',
        'Caisse Autonome d’Amortissement (CAA)',
        'Caisse de Stabilisation des Prix des Hydrocarbures (CSPH)',
        'Caisse Nationale de Prévoyance Sociale (CNPS)',
        'Cameroon Civil Aviation Authority (CCAA)',
        'Cameroon Development Corporation (CDC)',
        'Cameroon Hotels Corporation (CHC Hilton)',
        'Cameroon Postal Services (CAMPOST)',
        'Cameroon Telecommunications (CAMTEL)',
        'Cameroon Water Utilities Corporation (CAMWATER)',
        'Cameroun Airlines Corporation (CAMAIR-CO)',
        'Centrale Nationale d’Approvisionnement en Médicaments et Consommables Médicaux Essentiels (CENAME)',
        'Centre Hospitalier et Universitaire de Yaoundé (CHUY)',
        'Centre National d’Études et d’Expérimentation du Machinisme Agricole (CENEEMA)',
        'Centre National de Réhabilitation des Personnes Handicapées Paul-Émile-Léger (CNRPH)',
        'Centre Pasteur du Cameroun (CPC)',
        'Compagnie Camerounaise d’Aluminium (ALUCAM)',
        'Conseil National des Chargeurs du Cameroun (CNCC)',
        'Cotonnière Industrielle du Cameroun (CICAM)',
        'Crédit Foncier du Cameroun (CFC)',
        'Electricity Development Corporation (EDC)',
        'Fonds National de l’Emploi (FNE)',
        'Fonds Spécial d’Équipement et d’Intervention Intercommunale (FEICOM)',
        'Hôpital Général de Douala (HGD)',
        'Hôpital Général de Yaoundé (HGY)',
        'Hôpital Gynéco-Obstétrique et Pédiatrique de Douala (HGOPED)',
        'Hôpital Gynéco-Obstétrique et Pédiatrique de Yaoundé (HGOPY)',
        'Imprimerie Nationale',
        'Institut de Recherches Géologiques et Minières (IRGM)',
        'Institut de Recherches Médicales et d’Études des Plantes Médicinales (IMPM)',
        'Institut de Recherche Agricole pour le Développement (IRAD)',
        'Institut National de Cartographie (INC)',
        'Laboratoire National de Contrôle de Qualité des Médicaments et d’Expertise (LANACOME)',
        'Laboratoire National de Génie Civil (LABOGENIE)',
        'Laboratoire National Vétérinaire (LANAVET)',
        'Mission d’Aménagement et de Gestion des Zones Industrielles (MAGZI)',
        'Mission d’Aménagement et d’Équipement des Terrains Urbains et Ruraux (MAETUR)',
        'Mission d’Étude pour l’Aménagement de l’Océan (MEAO)',
        'Mission d’Études pour l’Aménagement de la Région du Nord (MEADEN)',
        'Mission de Développement de la Pêche Artisanale et Maritime (MIDEPECAM)',
        'Mission de Développement du Nord-Ouest (MIDENO)',
        'Mission de Développement Intégré des Monts Mandara (MIDIMA)',
        'Office de Radiodiffusion Télévision Camerounaise (CRTV)',
        'Pamol Plantations Plc (PAMOL)',
        'Parc National de Matériel de Génie Civil (MATGENIE)',
        'Port Autonome de Douala (PAD)',
        'Port Autonome de Kribi (PAK)',
        'Société Camerounaise des Dépôts Pétroliers (SCDP)',
        'Société de Développement du Cacao (SODECAO)',
        'Société de Développement du Coton du Cameroun (SODECOTON)',
        'Société d’Expansion et de Modernisation de la Riziculture de Yagoua (SEMRY)',
        'Société de Presse et d’Éditions du Cameroun (SOPECAM)',
        'Société de Recouvrement des Créances du Cameroun (SRC)',
        'Société Immobilière du Cameroun (SIC)',
        'Société Nationale d’Investissement (SNI)',
        'Société Nationale de Raffinage (SONARA)',
        'Société Nationale de Transport de l’Électricité (SONATREL)',
        'Société Nationale des Hydrocarbures (SNH)',
        'Société Nationale des Mines (SONAMINES)',
        'South West Development Authority (SOWEDA)',
        'Upper Nun Valley Development Authority (UNVDA)',
    ],
    'Universités d’État' => [
        'Université de Bamenda',
        'Université de Bertoua',
        'Université de Buea',
        'Université de Douala',
        'Université de Dschang',
        'Université d’Ebolowa',
        'Université de Garoua',
        'Université de Maroua',
        'Université de Ngaoundéré',
        'Université de Yaoundé I',
        'Université de Yaoundé II (Soa)',
    ],
];
