<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/*
 * Référentiel pays — 200+ entrées avec code ISO-2 et indicatif téléphonique.
 *
 * Source : docs/migration-candidature/seed-reference-data.md §2
 * Idempotent : upsert sur PK code_iso.
 */
class PaysSeeder extends Seeder
{
    public function run(): void
    {
        $pays = [
            ['code_iso' => 'AD', 'nom' => 'Andorre', 'indicatif' => '+376'],
            ['code_iso' => 'AE', 'nom' => 'Émirats arabes unis', 'indicatif' => '+971'],
            ['code_iso' => 'AF', 'nom' => 'Afghanistan', 'indicatif' => '+93'],
            ['code_iso' => 'AG', 'nom' => 'Antigua-et-Barbuda', 'indicatif' => '+1'],
            ['code_iso' => 'AL', 'nom' => 'Albanie', 'indicatif' => '+355'],
            ['code_iso' => 'AM', 'nom' => 'Arménie', 'indicatif' => '+374'],
            ['code_iso' => 'AO', 'nom' => 'Angola', 'indicatif' => '+244'],
            ['code_iso' => 'AR', 'nom' => 'Argentine', 'indicatif' => '+54'],
            ['code_iso' => 'AT', 'nom' => 'Autriche', 'indicatif' => '+43'],
            ['code_iso' => 'AU', 'nom' => 'Australie', 'indicatif' => '+61'],
            ['code_iso' => 'AZ', 'nom' => 'Azerbaïdjan', 'indicatif' => '+994'],
            ['code_iso' => 'BA', 'nom' => 'Bosnie-Herzégovine', 'indicatif' => '+387'],
            ['code_iso' => 'BB', 'nom' => 'Barbade', 'indicatif' => '+1'],
            ['code_iso' => 'BD', 'nom' => 'Bangladesh', 'indicatif' => '+880'],
            ['code_iso' => 'BE', 'nom' => 'Belgique', 'indicatif' => '+32'],
            ['code_iso' => 'BF', 'nom' => 'Burkina Faso', 'indicatif' => '+226'],
            ['code_iso' => 'BG', 'nom' => 'Bulgarie', 'indicatif' => '+359'],
            ['code_iso' => 'BH', 'nom' => 'Bahreïn', 'indicatif' => '+973'],
            ['code_iso' => 'BI', 'nom' => 'Burundi', 'indicatif' => '+257'],
            ['code_iso' => 'BJ', 'nom' => 'Bénin', 'indicatif' => '+229'],
            ['code_iso' => 'BN', 'nom' => 'Brunei', 'indicatif' => '+673'],
            ['code_iso' => 'BO', 'nom' => 'Bolivie', 'indicatif' => '+591'],
            ['code_iso' => 'BR', 'nom' => 'Brésil', 'indicatif' => '+55'],
            ['code_iso' => 'BS', 'nom' => 'Bahamas', 'indicatif' => '+1'],
            ['code_iso' => 'BT', 'nom' => 'Bhoutan', 'indicatif' => '+975'],
            ['code_iso' => 'BW', 'nom' => 'Botswana', 'indicatif' => '+267'],
            ['code_iso' => 'BY', 'nom' => 'Bélarus', 'indicatif' => '+375'],
            ['code_iso' => 'BZ', 'nom' => 'Belize', 'indicatif' => '+501'],
            ['code_iso' => 'CA', 'nom' => 'Canada', 'indicatif' => '+1'],
            ['code_iso' => 'CD', 'nom' => 'République Démocratique du Congo', 'indicatif' => '+243'],
            ['code_iso' => 'CF', 'nom' => 'République Centrafricaine', 'indicatif' => '+236'],
            ['code_iso' => 'CG', 'nom' => 'Congo', 'indicatif' => '+242'],
            ['code_iso' => 'CH', 'nom' => 'Suisse', 'indicatif' => '+41'],
            ['code_iso' => 'CI', 'nom' => "Côte d'Ivoire", 'indicatif' => '+225'],
            ['code_iso' => 'CL', 'nom' => 'Chili', 'indicatif' => '+56'],
            ['code_iso' => 'CM', 'nom' => 'Cameroun', 'indicatif' => '+237'],
            ['code_iso' => 'CN', 'nom' => 'Chine', 'indicatif' => '+86'],
            ['code_iso' => 'CO', 'nom' => 'Colombie', 'indicatif' => '+57'],
            ['code_iso' => 'CR', 'nom' => 'Costa Rica', 'indicatif' => '+506'],
            ['code_iso' => 'CU', 'nom' => 'Cuba', 'indicatif' => '+53'],
            ['code_iso' => 'CV', 'nom' => 'Cap-Vert', 'indicatif' => '+238'],
            ['code_iso' => 'CY', 'nom' => 'Chypre', 'indicatif' => '+357'],
            ['code_iso' => 'DE', 'nom' => 'Allemagne', 'indicatif' => '+49'],
            ['code_iso' => 'DJ', 'nom' => 'Djibouti', 'indicatif' => '+253'],
            ['code_iso' => 'DK', 'nom' => 'Danemark', 'indicatif' => '+45'],
            ['code_iso' => 'DM', 'nom' => 'Dominique', 'indicatif' => '+1'],
            ['code_iso' => 'DO', 'nom' => 'République Dominicaine', 'indicatif' => '+1'],
            ['code_iso' => 'DZ', 'nom' => 'Algérie', 'indicatif' => '+213'],
            ['code_iso' => 'EC', 'nom' => 'Équateur', 'indicatif' => '+593'],
            ['code_iso' => 'EE', 'nom' => 'Estonie', 'indicatif' => '+372'],
            ['code_iso' => 'EG', 'nom' => 'Égypte', 'indicatif' => '+20'],
            ['code_iso' => 'ER', 'nom' => 'Érythrée', 'indicatif' => '+291'],
            ['code_iso' => 'ES', 'nom' => 'Espagne', 'indicatif' => '+34'],
            ['code_iso' => 'ET', 'nom' => 'Éthiopie', 'indicatif' => '+251'],
            ['code_iso' => 'FI', 'nom' => 'Finlande', 'indicatif' => '+358'],
            ['code_iso' => 'FJ', 'nom' => 'Fidji', 'indicatif' => '+679'],
            ['code_iso' => 'FM', 'nom' => 'Micronésie', 'indicatif' => '+691'],
            ['code_iso' => 'FR', 'nom' => 'France', 'indicatif' => '+33'],
            ['code_iso' => 'GA', 'nom' => 'Gabon', 'indicatif' => '+241'],
            ['code_iso' => 'GB', 'nom' => 'Royaume-Uni', 'indicatif' => '+44'],
            ['code_iso' => 'GD', 'nom' => 'Grenade', 'indicatif' => '+1'],
            ['code_iso' => 'GE', 'nom' => 'Géorgie', 'indicatif' => '+995'],
            ['code_iso' => 'GH', 'nom' => 'Ghana', 'indicatif' => '+233'],
            ['code_iso' => 'GM', 'nom' => 'Gambie', 'indicatif' => '+220'],
            ['code_iso' => 'GN', 'nom' => 'Guinée', 'indicatif' => '+224'],
            ['code_iso' => 'GQ', 'nom' => 'Guinée Équatoriale', 'indicatif' => '+240'],
            ['code_iso' => 'GR', 'nom' => 'Grèce', 'indicatif' => '+30'],
            ['code_iso' => 'GT', 'nom' => 'Guatemala', 'indicatif' => '+502'],
            ['code_iso' => 'GW', 'nom' => 'Guinée-Bissau', 'indicatif' => '+245'],
            ['code_iso' => 'GY', 'nom' => 'Guyana', 'indicatif' => '+592'],
            ['code_iso' => 'HN', 'nom' => 'Honduras', 'indicatif' => '+504'],
            ['code_iso' => 'HR', 'nom' => 'Croatie', 'indicatif' => '+385'],
            ['code_iso' => 'HT', 'nom' => 'Haïti', 'indicatif' => '+509'],
            ['code_iso' => 'HU', 'nom' => 'Hongrie', 'indicatif' => '+36'],
            ['code_iso' => 'ID', 'nom' => 'Indonésie', 'indicatif' => '+62'],
            ['code_iso' => 'IE', 'nom' => 'Irlande', 'indicatif' => '+353'],
            ['code_iso' => 'IL', 'nom' => 'Israël', 'indicatif' => '+972'],
            ['code_iso' => 'IN', 'nom' => 'Inde', 'indicatif' => '+91'],
            ['code_iso' => 'IQ', 'nom' => 'Irak', 'indicatif' => '+964'],
            ['code_iso' => 'IR', 'nom' => 'Iran', 'indicatif' => '+98'],
            ['code_iso' => 'IS', 'nom' => 'Islande', 'indicatif' => '+354'],
            ['code_iso' => 'IT', 'nom' => 'Italie', 'indicatif' => '+39'],
            ['code_iso' => 'JM', 'nom' => 'Jamaïque', 'indicatif' => '+1'],
            ['code_iso' => 'JO', 'nom' => 'Jordanie', 'indicatif' => '+962'],
            ['code_iso' => 'JP', 'nom' => 'Japon', 'indicatif' => '+81'],
            ['code_iso' => 'KE', 'nom' => 'Kenya', 'indicatif' => '+254'],
            ['code_iso' => 'KG', 'nom' => 'Kirghizistan', 'indicatif' => '+996'],
            ['code_iso' => 'KH', 'nom' => 'Cambodge', 'indicatif' => '+855'],
            ['code_iso' => 'KI', 'nom' => 'Kiribati', 'indicatif' => '+686'],
            ['code_iso' => 'KM', 'nom' => 'Comores', 'indicatif' => '+269'],
            ['code_iso' => 'KN', 'nom' => 'Saint-Christophe-et-Niévès', 'indicatif' => '+1'],
            ['code_iso' => 'KP', 'nom' => 'Corée du Nord', 'indicatif' => '+850'],
            ['code_iso' => 'KR', 'nom' => 'Corée du Sud', 'indicatif' => '+82'],
            ['code_iso' => 'KW', 'nom' => 'Koweït', 'indicatif' => '+965'],
            ['code_iso' => 'KZ', 'nom' => 'Kazakhstan', 'indicatif' => '+7'],
            ['code_iso' => 'LA', 'nom' => 'Laos', 'indicatif' => '+856'],
            ['code_iso' => 'LB', 'nom' => 'Liban', 'indicatif' => '+961'],
            ['code_iso' => 'LC', 'nom' => 'Sainte-Lucie', 'indicatif' => '+1'],
            ['code_iso' => 'LI', 'nom' => 'Liechtenstein', 'indicatif' => '+423'],
            ['code_iso' => 'LK', 'nom' => 'Sri Lanka', 'indicatif' => '+94'],
            ['code_iso' => 'LR', 'nom' => 'Libéria', 'indicatif' => '+231'],
            ['code_iso' => 'LS', 'nom' => 'Lesotho', 'indicatif' => '+266'],
            ['code_iso' => 'LT', 'nom' => 'Lituanie', 'indicatif' => '+370'],
            ['code_iso' => 'LU', 'nom' => 'Luxembourg', 'indicatif' => '+352'],
            ['code_iso' => 'LV', 'nom' => 'Lettonie', 'indicatif' => '+371'],
            ['code_iso' => 'LY', 'nom' => 'Libye', 'indicatif' => '+218'],
            ['code_iso' => 'MA', 'nom' => 'Maroc', 'indicatif' => '+212'],
            ['code_iso' => 'MC', 'nom' => 'Monaco', 'indicatif' => '+377'],
            ['code_iso' => 'MD', 'nom' => 'Moldavie', 'indicatif' => '+373'],
            ['code_iso' => 'ME', 'nom' => 'Monténégro', 'indicatif' => '+382'],
            ['code_iso' => 'MG', 'nom' => 'Madagascar', 'indicatif' => '+261'],
            ['code_iso' => 'MH', 'nom' => 'Îles Marshall', 'indicatif' => '+692'],
            ['code_iso' => 'MK', 'nom' => 'Macédoine du Nord', 'indicatif' => '+389'],
            ['code_iso' => 'ML', 'nom' => 'Mali', 'indicatif' => '+223'],
            ['code_iso' => 'MM', 'nom' => 'Myanmar (Birmanie)', 'indicatif' => '+95'],
            ['code_iso' => 'MN', 'nom' => 'Mongolie', 'indicatif' => '+976'],
            ['code_iso' => 'MR', 'nom' => 'Mauritanie', 'indicatif' => '+222'],
            ['code_iso' => 'MT', 'nom' => 'Malte', 'indicatif' => '+356'],
            ['code_iso' => 'MU', 'nom' => 'Maurice', 'indicatif' => '+230'],
            ['code_iso' => 'MV', 'nom' => 'Maldives', 'indicatif' => '+960'],
            ['code_iso' => 'MW', 'nom' => 'Malawi', 'indicatif' => '+265'],
            ['code_iso' => 'MX', 'nom' => 'Mexique', 'indicatif' => '+52'],
            ['code_iso' => 'MY', 'nom' => 'Malaisie', 'indicatif' => '+60'],
            ['code_iso' => 'MZ', 'nom' => 'Mozambique', 'indicatif' => '+258'],
            ['code_iso' => 'NA', 'nom' => 'Namibie', 'indicatif' => '+264'],
            ['code_iso' => 'NE', 'nom' => 'Niger', 'indicatif' => '+227'],
            ['code_iso' => 'NG', 'nom' => 'Nigéria', 'indicatif' => '+234'],
            ['code_iso' => 'NI', 'nom' => 'Nicaragua', 'indicatif' => '+505'],
            ['code_iso' => 'NL', 'nom' => 'Pays-Bas', 'indicatif' => '+31'],
            ['code_iso' => 'NO', 'nom' => 'Norvège', 'indicatif' => '+47'],
            ['code_iso' => 'NP', 'nom' => 'Népal', 'indicatif' => '+977'],
            ['code_iso' => 'NR', 'nom' => 'Nauru', 'indicatif' => '+674'],
            ['code_iso' => 'NZ', 'nom' => 'Nouvelle-Zélande', 'indicatif' => '+64'],
            ['code_iso' => 'OM', 'nom' => 'Oman', 'indicatif' => '+968'],
            ['code_iso' => 'PA', 'nom' => 'Panama', 'indicatif' => '+507'],
            ['code_iso' => 'PE', 'nom' => 'Pérou', 'indicatif' => '+51'],
            ['code_iso' => 'PG', 'nom' => 'Papouasie-Nouvelle-Guinée', 'indicatif' => '+675'],
            ['code_iso' => 'PH', 'nom' => 'Philippines', 'indicatif' => '+63'],
            ['code_iso' => 'PK', 'nom' => 'Pakistan', 'indicatif' => '+92'],
            ['code_iso' => 'PL', 'nom' => 'Pologne', 'indicatif' => '+48'],
            ['code_iso' => 'PT', 'nom' => 'Portugal', 'indicatif' => '+351'],
            ['code_iso' => 'PW', 'nom' => 'Palaos', 'indicatif' => '+680'],
            ['code_iso' => 'PY', 'nom' => 'Paraguay', 'indicatif' => '+595'],
            ['code_iso' => 'QA', 'nom' => 'Qatar', 'indicatif' => '+974'],
            ['code_iso' => 'RO', 'nom' => 'Roumanie', 'indicatif' => '+40'],
            ['code_iso' => 'RS', 'nom' => 'Serbie', 'indicatif' => '+381'],
            ['code_iso' => 'RU', 'nom' => 'Russie', 'indicatif' => '+7'],
            ['code_iso' => 'RW', 'nom' => 'Rwanda', 'indicatif' => '+250'],
            ['code_iso' => 'SA', 'nom' => 'Arabie Saoudite', 'indicatif' => '+966'],
            ['code_iso' => 'SB', 'nom' => 'Îles Salomon', 'indicatif' => '+677'],
            ['code_iso' => 'SC', 'nom' => 'Seychelles', 'indicatif' => '+248'],
            ['code_iso' => 'SD', 'nom' => 'Soudan', 'indicatif' => '+249'],
            ['code_iso' => 'SE', 'nom' => 'Suède', 'indicatif' => '+46'],
            ['code_iso' => 'SG', 'nom' => 'Singapour', 'indicatif' => '+65'],
            ['code_iso' => 'SI', 'nom' => 'Slovénie', 'indicatif' => '+386'],
            ['code_iso' => 'SK', 'nom' => 'Slovaquie', 'indicatif' => '+421'],
            ['code_iso' => 'SL', 'nom' => 'Sierra Leone', 'indicatif' => '+232'],
            ['code_iso' => 'SM', 'nom' => 'Saint-Marin', 'indicatif' => '+378'],
            ['code_iso' => 'SN', 'nom' => 'Sénégal', 'indicatif' => '+221'],
            ['code_iso' => 'SO', 'nom' => 'Somalie', 'indicatif' => '+252'],
            ['code_iso' => 'SR', 'nom' => 'Suriname', 'indicatif' => '+597'],
            ['code_iso' => 'SS', 'nom' => 'Soudan du Sud', 'indicatif' => '+211'],
            ['code_iso' => 'ST', 'nom' => 'Sao Tomé-et-Principe', 'indicatif' => '+239'],
            ['code_iso' => 'SV', 'nom' => 'Salvador', 'indicatif' => '+503'],
            ['code_iso' => 'SY', 'nom' => 'Syrie', 'indicatif' => '+963'],
            ['code_iso' => 'SZ', 'nom' => 'Eswatini', 'indicatif' => '+268'],
            ['code_iso' => 'TD', 'nom' => 'Tchad', 'indicatif' => '+235'],
            ['code_iso' => 'TG', 'nom' => 'Togo', 'indicatif' => '+228'],
            ['code_iso' => 'TH', 'nom' => 'Thaïlande', 'indicatif' => '+66'],
            ['code_iso' => 'TJ', 'nom' => 'Tadjikistan', 'indicatif' => '+992'],
            ['code_iso' => 'TL', 'nom' => 'Timor oriental', 'indicatif' => '+670'],
            ['code_iso' => 'TM', 'nom' => 'Turkménistan', 'indicatif' => '+993'],
            ['code_iso' => 'TN', 'nom' => 'Tunisie', 'indicatif' => '+216'],
            ['code_iso' => 'TO', 'nom' => 'Tonga', 'indicatif' => '+676'],
            ['code_iso' => 'TR', 'nom' => 'Turquie', 'indicatif' => '+90'],
            ['code_iso' => 'TT', 'nom' => 'Trinité-et-Tobago', 'indicatif' => '+1'],
            ['code_iso' => 'TV', 'nom' => 'Tuvalu', 'indicatif' => '+688'],
            ['code_iso' => 'TW', 'nom' => 'Taïwan', 'indicatif' => '+886'],
            ['code_iso' => 'TZ', 'nom' => 'Tanzanie', 'indicatif' => '+255'],
            ['code_iso' => 'UA', 'nom' => 'Ukraine', 'indicatif' => '+380'],
            ['code_iso' => 'UG', 'nom' => 'Ouganda', 'indicatif' => '+256'],
            ['code_iso' => 'US', 'nom' => 'États-Unis', 'indicatif' => '+1'],
            ['code_iso' => 'UY', 'nom' => 'Uruguay', 'indicatif' => '+598'],
            ['code_iso' => 'UZ', 'nom' => 'Ouzbékistan', 'indicatif' => '+998'],
            ['code_iso' => 'VA', 'nom' => 'Vatican', 'indicatif' => '+379'],
            ['code_iso' => 'VC', 'nom' => 'Saint-Vincent-et-les-Grenadines', 'indicatif' => '+1'],
            ['code_iso' => 'VE', 'nom' => 'Venezuela', 'indicatif' => '+58'],
            ['code_iso' => 'VN', 'nom' => 'Vietnam', 'indicatif' => '+84'],
            ['code_iso' => 'VU', 'nom' => 'Vanuatu', 'indicatif' => '+678'],
            ['code_iso' => 'WS', 'nom' => 'Samoa', 'indicatif' => '+685'],
            ['code_iso' => 'XK', 'nom' => 'Kosovo', 'indicatif' => '+383'],
            ['code_iso' => 'YE', 'nom' => 'Yémen', 'indicatif' => '+967'],
            ['code_iso' => 'ZA', 'nom' => 'Afrique du Sud', 'indicatif' => '+27'],
            ['code_iso' => 'ZM', 'nom' => 'Zambie', 'indicatif' => '+260'],
            ['code_iso' => 'ZW', 'nom' => 'Zimbabwe', 'indicatif' => '+263'],
        ];

        $now = now();
        foreach (array_chunk($pays, 50) as $chunk) {
            $rows = array_map(
                fn ($p) => array_merge($p, ['created_at' => $now, 'updated_at' => $now]),
                $chunk
            );
            DB::table('pays')->upsert($rows, ['code_iso'], ['nom', 'indicatif', 'updated_at']);
        }
    }
}
